import Image from 'next/image'
import React from 'react'

function HomeBanner() {
    return (
        <div className="elementor-element elementor-element-a71a37a e-con-full e-flex e-con" data-id="a71a37a" data-element_type="container" data-settings="{&quot;content_width&quot;:&quot;full&quot;}">
            <div className="elementor-element elementor-element-29c8aae elementor-widget elementor-widget-slider_revolution" data-id="29c8aae" data-element_type="widget" data-widget_type="slider_revolution.default">
                <div className="elementor-widget-container">
                    <div className="wp-block-themepunch-revslider">
                        <p className="rs-p-wp-fix"></p>
                        <rs-module-wrap id="rev_slider_4_1_wrapper" data-source="gallery" style={{visibility:'hidden',background:'transparent',padding:0,margin:"0px auto",marginTop:0,marginBottom:0}}>
                            <rs-module id="rev_slider_4_1" data-version="6.6.15">
                                <rs-slides style={{overflow: "hidden", position: "absolute"}}>
                                    <rs-slide style={{position: "absolute"}} data-key="rs-4" data-title="Slide" data-anim="ms:1700ms;f:center;" data-in="o:0;sx:1.1;sy:1.1;m:true;row:30;col:30;" data-out="a:false;">
                                        <img decoding="async" fetchPriority="high" src="/assets/images/dummy.png" alt="" title="img-slider4-1-min" width="1920" height="1000" className="rev-slidebg tp-rs-img rs-lazyload" data-lazyload="/assets/images/slider1.jpg" data-no-retina=""/>
                                            <rs-group id="slider-4-slide-4-layer-3" data-type="group" data-xy="x:l,l,l,c;xo:315px,30px,50px,0;y:b;yo:75px,40px,70px,30px;" data-text="w:normal;s:20,10,7,4;l:0,13,9,6;" data-dim="w:122px,130px,130px,160px;h:50px;" data-vbility="t,t,t,f" data-rsp_bd="off" data-frame_0="o:1;" data-frame_999="o:0;st:w;sA:6000;" style={{zIndex:7}}><rs-layer id="slider-4-slide-4-layer-10" data-type="text" data-color="#221d1a" data-xy="x:c;y:m;" data-pos="a" data-text="w:normal;s:14;l:18;fw:600;" data-rsp_bd="off" data-frame_999="o:0;st:w;" style={{zIndex:8,fontFamily:'Montserrat'}}>01/03
                                            </rs-layer><rs-layer id="slider-4-slide-4-layer-11" data-type="button" data-color="#221d1a" data-xy="x:r;y:m;" data-pos="a" data-text="w:normal;s:18;l:50;fw:500;" data-actions="o:click;a:jumptoslide;slide:rs-11;" data-rsp_bd="off" data-padding="l:15;" data-frame_999="o:0;st:w;" data-frame_hover="c:#bd7655;" style={{zIndex:7,fontFamily:'Roboto'}}><i className="material-icons">arrow_forward</i>
                                                </rs-layer><rs-layer id="slider-4-slide-4-layer-9" data-type="button" data-color="#221d1a" data-xy="y:m;" data-pos="a" data-text="w:normal;s:18;l:50;fw:500;" data-actions="o:click;a:jumptoslide;slide:rs-12;" data-rsp_bd="off" data-padding="r:15;" data-frame_999="o:0;st:w;" data-frame_hover="c:#bd7655;" style={{zIndex:6,fontFamily:'Roboto'}}><i className="material-icons">arrow_back</i>
                                                </rs-layer></rs-group> </rs-slide>
                                    <rs-slide style={{position: "absolute"}} data-key="rs-11" data-title="Slide" data-anim="ms:1700ms;f:center;" data-in="o:0;sx:1.1;sy:1.1;m:true;row:30;col:30;" data-out="a:false;">
                                        <img decoding="async" src="/assets/images/dummy.png" alt="" title="img-slider4-2-min" width="1920" height="1000" className="rev-slidebg tp-rs-img rs-lazyload" data-lazyload="/assets/images/slider2.jpg" data-no-retina=""/>
                                            <rs-group id="slider-4-slide-11-layer-3" data-type="group" data-xy="x:l,l,l,c;xo:315px,30px,50px,0;y:b;yo:75px,40px,70px,30px;" data-text="w:normal;s:20,10,7,4;l:0,13,9,6;" data-dim="w:122px,130px,130px,160px;h:50px;" data-vbility="t,t,t,f" data-rsp_bd="off" data-frame_0="o:1;" data-frame_999="o:0;st:w;sA:6000;" style={{zIndex:7}}><rs-layer id="slider-4-slide-11-layer-10" data-type="text" data-color="#221d1a" data-xy="x:c;y:m;" data-pos="a" data-text="w:normal;s:14;l:18;fw:600;" data-rsp_bd="off" data-frame_999="o:0;st:w;" style={{zIndex:8,fontFamily:'Montserrat'}}>02/03
                                            </rs-layer><rs-layer id="slider-4-slide-11-layer-11" data-type="button" data-color="#221d1a" data-xy="x:r;y:m;" data-pos="a" data-text="w:normal;s:18;l:50;fw:500;" data-actions="o:click;a:jumptoslide;slide:rs-12;" data-rsp_bd="off" data-padding="l:15;" data-frame_999="o:0;st:w;" data-frame_hover="c:#bd7655;" style={{zIndex:7,fontFamily:'Roboto'}}><i className="material-icons">arrow_forward</i>
                                                </rs-layer><rs-layer id="slider-4-slide-11-layer-9" data-type="button" data-color="#221d1a" data-xy="y:m;" data-pos="a" data-text="w:normal;s:18;l:50;fw:500;" data-actions="o:click;a:jumptoslide;slide:rs-4;" data-rsp_bd="off" data-padding="r:15;" data-frame_999="o:0;st:w;" data-frame_hover="c:#bd7655;" style={{zIndex:6,fontFamily:'Roboto'}}><i className="material-icons">arrow_back</i>
                                                </rs-layer></rs-group> </rs-slide>
                                    <rs-slide style={{position: "absolute"}} data-key="rs-12" data-title="Slide" data-anim="ms:1700ms;f:center;" data-in="o:0;sx:1.1;sy:1.1;m:true;row:30;col:30;" data-out="a:false;">
                                        <img decoding="async" src="/assets/images/dummy.png" alt="" title="img-slider4-3-min" width="1920" height="1000" className="rev-slidebg tp-rs-img rs-lazyload" data-lazyload="/assets/images/slider3.jpg" data-no-retina=""/>
                                            <rs-group id="slider-4-slide-12-layer-3" data-type="group" data-xy="x:l,l,l,c;xo:315px,30px,50px,0;y:b;yo:75px,40px,70px,30px;" data-text="w:normal;s:20,10,7,4;l:0,13,9,6;" data-dim="w:122px,130px,130px,160px;h:50px;" data-vbility="t,t,t,f" data-rsp_bd="off" data-frame_0="o:1;" data-frame_999="o:0;st:w;sA:6000;" style={{zIndex:7}}><rs-layer id="slider-4-slide-12-layer-10" data-type="text" data-color="#221d1a" data-xy="x:c;y:m;" data-pos="a" data-text="w:normal;s:14;l:18;fw:600;" data-rsp_bd="off" data-frame_999="o:0;st:w;" style={{zIndex:8,fontFamily:'Montserrat'}}>03/03
                                            </rs-layer><rs-layer id="slider-4-slide-12-layer-11" data-type="button" data-color="#221d1a" data-xy="x:r;y:m;" data-pos="a" data-text="w:normal;s:18;l:50;fw:500;" data-actions="o:click;a:jumptoslide;slide:rs-4;" data-rsp_bd="off" data-padding="l:15;" data-frame_999="o:0;st:w;" data-frame_hover="c:#bd7655;" style={{zIndex:7,fontFamily:'Roboto'}}><i className="material-icons">arrow_forward</i>
                                                </rs-layer><rs-layer id="slider-4-slide-12-layer-9" data-type="button" data-color="#221d1a" data-xy="y:m;" data-pos="a" data-text="w:normal;s:18;l:50;fw:500;" data-actions="o:click;a:jumptoslide;slide:rs-11;" data-rsp_bd="off" data-padding="r:15;" data-frame_999="o:0;st:w;" data-frame_hover="c:#bd7655;" style={{zIndex:6,fontFamily:'Roboto'}}><i className="material-icons">arrow_back</i>
                                                </rs-layer></rs-group> </rs-slide>
                                </rs-slides>
                                <rs-static-layers><rs-zone id="rrzm_4" className="rev_row_zone_middle" style={{zIndex: 5}}><rs-row id="slider-4-slide-4-layer-12" className="rs-layer-static" data-type="row" data-xy="xo:50px;yo:50px;" data-rsp_bd="off" data-onslides="s:1;" data-margin="t:33;" data-frame_0="o:1;" data-frame_999="o:0;st:w;sR:5700;sA:6000;" style={{zIndex:6}}><rs-column id="slider-4-slide-4-layer-13" className="rs-layer-static" data-type="column" data-xy="xo:50px;yo:50px;" data-vbility="t,f,f,f" data-onslides="s:1;" data-column="w:16.67%;" data-padding="t:10;r:10;b:10;l:10;" data-frame_0="o:1;" data-frame_999="o:0;st:w;sR:8700;sA:6000;" style={{zIndex:7,width:"100%"}}></rs-column><rs-column id="slider-4-slide-4-layer-14" className="rs-layer-static" data-type="column" data-xy="xo:50px;yo:50px;" data-text="a:left,left,left,center;" data-rsp_bd="off" data-onslides="s:1;" data-column="w:83.33%;" data-margin="r:0,0,0,15;l:0,30,50,15;" data-frame_0="o:1;" data-frame_999="o:0;st:w;sR:8700;sA:6000;" style={{zIndex:6,width:"100%"}}><rs-layer id="slider-4-slide-4-layer-15" className="rs-layer-static" data-type="text" data-color="orange" data-rsp_ch="on" data-xy="" data-pos="r" data-text="w:normal;s:95,75,56,56;l:95,75,56,56;ls:-1px,0px,0px,0px;a:left,left,left,center;" data-dim="w:531px,367px,463px,auto;" data-rsp_o="off" data-onslides="s:1;" data-disp="inline-block" data-frame_0="x:175%;o:1;" data-frame_0_mask="u:t;x:-100%;" data-frame_1="e:power3.out;st:330;sp:1800;" data-frame_1_mask="u:t;" data-frame_999="o:0;st:w;sR:6870;" style={{zIndex:2,fontFamily:'Oranienbaum',textTransform:'capitalize',display:"inline-block"}}>
                                    The Story of modern stylish Salon
                                </rs-layer><rs-layer id="slider-4-slide-4-layer-18" className="rs-layer-static" data-type="shape" data-rsp_ch="on" data-xy="xo:50px,26px,19px,11px;yo:50px,26px,19px,11px;" data-pos="r" data-text="w:normal;s:20,10,7,4;c:both;l:0,13,9,6;" data-flcr="c:both;" data-dim="w:100%;h:26px,13px,15px,15px;" data-onslides="s:1;" data-frame_999="o:0;st:w;sR:8700;" style={{zIndex:9}}>
                                    </rs-layer><rs-layer id="slider-4-slide-4-layer-16" className="rs-layer-static" data-type="text" data-color="#fff" data-xy="" data-pos="r" data-text="w:normal;s:18;l:26;a:left,left,left,center;" data-dim="w:457px,375px,361px,auto;" data-rsp_o="off" data-rsp_bd="off" data-onslides="s:1;" data-disp="inline-block" data-frame_0="x:175%;o:1;" data-frame_0_mask="u:t;x:-100%;" data-frame_1="e:power3.out;st:550;sp:1800;" data-frame_1_mask="u:t;" data-frame_999="o:0;st:w;sR:6650;" style={{zIndex:8,fontFamily:'Montserrat',display:"inline-block"}}>
                                        The Tale of the Chic Modern SalonExpert stylists in a lighthearted and welcoming setting. This is something you deserve.
                                    </rs-layer><rs-layer id="slider-4-slide-4-layer-19" className="rs-layer-static" data-type="shape" data-rsp_ch="on" data-xy="xo:50px,26px,19px,11px;yo:50px,26px,19px,11px;" data-pos="r" data-text="w:normal;s:20,10,7,4;c:both;l:0,13,9,6;" data-flcr="c:both;" data-dim="w:100%;h:57px,30px,22px,28px;" data-onslides="s:1;" data-frame_999="o:0;st:w;sR:8700;" style={{zIndex:7}}>
                                    </rs-layer><a id="slider-4-slide-4-layer-17" className="rs-layer rev-btn rs-layer-static" href="/services.html" target="_self" data-type="button" data-color="#fff" data-xy="" data-pos="r" data-text="w:normal;s:12;l:20;ls:1px,0px,0px,0px;fw:600;a:left,left,left,center;" data-dim="minh:0px,none,none,none;" data-rsp_o="off" data-rsp_bd="off" data-onslides="s:1;" data-disp="inline-block" data-padding="t:17,17,15,15;r:40,40,35,35;b:17,17,15,15;l:40,40,35,35;" data-border="bos:solid;boc:#575351;bow:1px,1px,1px,1px;" data-frame_0="x:175%;o:1;" data-frame_0_mask="u:t;x:-100%;" data-frame_1="e:power3.out;st:900;sp:1800;" data-frame_1_mask="u:t;" data-frame_999="o:0;st:w;sR:6300;" data-frame_hover="c:#fff;bgc:#bd7655;boc:#bd7655;bor:0px,0px,0px,0px;bos:solid;bow:1px,1px,1px,1px;e:power1.inOut;" style={{zIndex:6,backgroundColor:"rgba(0,0,0,0)",fontFamily:'Montserrat',textTransform:"uppercase",display:"inline-block"}}>
                                        Shop Now
                                    </a></rs-column></rs-row></rs-zone></rs-static-layers>
                            </rs-module>
                            <script>
                                {` setREVStartSize({ c: 'rev_slider_4_1', rl: [1240, 1025, 778, 480], el: [1000, 768, 780, 720], gw: [1920, 1024, 778, 480], gh: [1000, 768, 780, 720], type: 'standard', justify: '', layout: 'fullwidth', mh: "0" }); if (window.RS_MODULES !== undefined && window.RS_MODULES.modules !== undefined && window.RS_MODULES.modules["revslider41"] !== undefined) { window.RS_MODULES.modules["revslider41"].once = false; window.revapi4 = undefined; if (window.RS_MODULES.checkMinimal !== undefined) window.RS_MODULES.checkMinimal() }`}
                            </script>
                        </rs-module-wrap>

                    </div>
                </div>
            </div>
        </div>
    )
}

export default HomeBanner